//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HIC.Lang_en_US", typeof(Lang_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help is coming!.
        /// </summary>
        internal static string appTitle {
            get {
                return ResourceManager.GetString("appTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmit {
            get {
                return ResourceManager.GetString("btnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact me at:.
        /// </summary>
        internal static string cbxCallMeBack {
            get {
                return ResourceManager.GetString("cbxCallMeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach screenshot to report.
        /// </summary>
        internal static string cbxScreenShot {
            get {
                return ResourceManager.GetString("cbxScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sent report; please call the helpdesk to get assistance..
        /// </summary>
        internal static string errFailSent {
            get {
                return ResourceManager.GetString("errFailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short description is required inorder for us to help you quickly resolve the issue..
        /// </summary>
        internal static string errNonDescription {
            get {
                return ResourceManager.GetString("errNonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide short description of your problem..
        /// </summary>
        internal static string lblWelkomText {
            get {
                return ResourceManager.GetString("lblWelkomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;[D]\[U]&quot; reported an issue via HIC that needs investigation..
        /// </summary>
        internal static string rptBody {
            get {
                return ResourceManager.GetString("rptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user could like to be contacted at: .
        /// </summary>
        internal static string rptContactUser {
            get {
                return ResourceManager.GetString("rptContactUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIC Report.
        /// </summary>
        internal static string rptSubject {
            get {
                return ResourceManager.GetString("rptSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [!].
        /// </summary>
        internal static string rptSubjectMark {
            get {
                return ResourceManager.GetString("rptSubjectMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (xxx) xxx-xxxx.
        /// </summary>
        internal static string tbxContactDetail {
            get {
                return ResourceManager.GetString("tbxContactDetail", resourceCulture);
            }
        }
    }
}
